{% set name = "aliyun-python-sdk-core" %}
{% set version = "2.13.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15bab6bab827a3ea737fb1618e44866a7d7af54ba4cf60d086a65718ef43ff19

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jmespath >=0.9.3,<1.0.0
    - pycryptodome >=3.4.7  # [unix]

test:
  imports:
    - aliyunsdkcore

about:
  home: https://github.com/aliyun/aliyun-openapi-python-sdk
  license: Apache-2.0
  license_file: LICENSE
  summary: 'The core module of Aliyun Python SDK.'

  description: |
    The Alibaba Cloud Python Software Development Kit (SDK) allows you to
    access Alibaba Cloud services such as Elastic Compute Service (ECS),
    Object Storage Service (OSS), and Resource Access Management (RAM).
    You can access Alibaba Cloud services without the need to handle API
    related tasks, such as signing and constructing your requests.

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
    - MaxRis
