{% set name = "aliyun-python-sdk-core" %}
{% set version = "2.13.34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07f34ad63752be8bc23ccefa925a5d18e02a619d35f2f87cd28f8d320deb2442

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jmespath >=0.9.3,<1.0.0
    - cryptography >=2.9.2

test:
  imports:
    - aliyunsdkcore

about:
  home: https://github.com/aliyun/aliyun-openapi-python-sdk
  license: Apache-2.0
  license_file: LICENSE
  summary: The core module of Aliyun Python SDK.

  description: |
    The Alibaba Cloud Python Software Development Kit (SDK) allows you to
    access Alibaba Cloud services such as Elastic Compute Service (ECS),
    Object Storage Service (OSS), and Resource Access Management (RAM).
    You can access Alibaba Cloud services without the need to handle API
    related tasks, such as signing and constructing your requests.

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
    - maxhora
