travis:
  secure:
    BINSTAR_TOKEN: bVE8EDv69E0zEgxj/slh+Nyms2YXQGqd7Vm2ytosoeHj7zaCWxkLKSZQLv9juAyWkm4WsQzZ08IOxV6qzIB0mPTasXiN6DvLbUNUhjzwmeJnYTMjPBhqC6B/3Dc6e6rmRw0BpIoKjev/zgpzt2dX3m4d+XaXTAyUXnNaHLIgRtcMOjjcfTIHrekvg2YqfbYs+IgnQRfUJpfDa5H3u9UynNTd+/OWWL9Bv4Z2/Csie1Xm/ILNwMg3GPw3wNAtdxjeN8nzSxOFq89pkYkj3Nyvkhz3uE2BE0k4wFiBnNkqaM6UWWkagvptyL9N1y9Q2pKuZ7rmfibIkAjoXWCdqGe79+KeKHBP3pwt827ujbJW3QuyCjRdaW+TgnqraWhLLNYg0YaDzn11YDMdwVp3PjX3L5Zqt2g/cltD2tBVOlsblSL7ZF/XFgEvwMo/DNT6w90rCxrVi+kDlldc0knfpf8IUMHvP/svDkog9QlIWWV7xjp1K9InDcL0Q2FhR07c5vK2V0CgEonLUYr08ds41UQdHqvuNQfFE454tNoU0ctG2WW0fMJ78cwrlUs+GzlpLk4mz0OXRnmxwwhzc0Ewit/lyZyAcZqZkjjBW2Ly1MzAsrtCdeCLPGBYyUWYw4jh61FOx++JbwnQaTELjXnGpI6vO6ITLfS/ovBATtPo52llPwg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
bot:
  automerge: true
